### ISSUE TITLE
Checkmark persistence depends on list indent level.

### ISSUE THREAD

**Issue by RainerBielefeld** [creecros/MarkdownPlus#38]
# Try following Task code in your own KANBOARD Installation:!

## STR: 
1. Check all boxes   
   » As expected all get checkmarks  
2. Refresh page in Browser   
   » Expected: All Checkmarks will persist   
   Actual: several Checkmarks lost  😥  
3. And when you now click the remaining checkmarks they will disapper as expected 
4. Refresh Browser Page   
   » Expected:  no Checkmarks at all
   Actual: Checkmarks "deleted" in step 3 reappear  😥  

The code for your tests
```
In a Comment in a List I had checkmarks:  
* Here  
   * [ ] is a checkbox  
* And here  
   * [ ] is a second one.  

---

Works fine on first list level
* [ ] is a checkbox  
   * [ ] is a second one
      * [ ] is a third one
         * [ ] is a fourh checkbox  
            * [ ] is a fifth  one
                * [ ] is a sixth one
```

And finally: let's see wjat happens here:

In a Comment in a List I had checkmarks:  
* Here  
   * [ ] is a checkbox  
* And here  
   * [ ] is a second one.  

---

Works fine on first list level
* [ ] is a checkbox  
   * [ ] is a second one
      * [ ] is a third one
         * [ ] is a fourh checkbox  
            * [ ] is a fifth  one
                * [ ] is a sixth one

**Comment by RainerBielefeld** [comment]
## My Configuration  
* Application version:  1.2.43 ,  installed at hoster [All-Inkl](https://all-inkl.com/)  
* PHP version:  8.3.14-nmm1  
* PHP SAPI: fpm-fcgi  
* HTTP Client: cURL  
* OS Version: Linux 6.8.0-51-generic
* Database driver: mysql  
* Datenbank Version: 10.11.8-MariaDB-0ubuntu0.24.04.1-log
* Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:117.0a) Gecko/20100101 SeaMonkey/2.53.19, Build 20240329110002; Same with FF Trunk (135.0a1 (2024-12-24) (64-Bit)),    
  
* Profile Language: German - DU
* [Plugins](https://kanboard.org/plugins.html):   
   * MarkdownPlus 1.1.5

**Comment by RainerBielefeld** [comment]
# Side effect  
## Checkmarks do not persists in enumerations, either!  

### Task Code:   
(I tested in a Comment)  


```

[x] A1 

1. [ ] A1  
2.  [ ] A2  
3.  [ ] A3  
   3.1.  [ ] A3.1  
        3.1.1.  [ ] A3.1.1  
4. x
  
```
